# ML lab 08: Tensor Manipulation

In [17]:
import numpy as np
import pprint
import tensorflow as tf
tf.set_random_seed(7747) # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

## simple Array

In [18]:
# Simple ID array and slicing
t = np.array([0,1,2,3,4,5,6])
pp.pprint(t)
print(t.ndim) # rank (dimension)
print(t.shape) # shape (length)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0, 1, 2, 3, 4, 5, 6])
1
(7,)
0 1 6
[2 3 4] [4 5]
[0 1] [3 4 5 6]


## 2D Array

In [19]:
# 2D Array
t = np.array([[1., 2., 3.], [4., 5., 6.], [7.,8.,9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank (dimension)
print(t.shape) # shape (length)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


## Shape, Rank, Axis

In [24]:
# Sahpe, Rank, Axis
t = tf.constant([1,2,3,4]) # rank = 1, shape = 4
tf.shape(t).eval()

array([4])

In [21]:
t = tf.constant([[1,2], # rank = 2, shape = (2,2)
                [3,4]])
tf.shape(t).eval()

array([2, 2])

In [22]:
t = tf.constant([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                [[13,14,15,16],[17,18,19,20], [21,22,23,24]]]])  # rank = 4, shape(1,2,3,4), axis = 3
tf.shape(t).eval()

array([1, 2, 3, 4])

In [23]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

## Matmul VS multiply

In [25]:
# Matmul VS multiply
matrix1 = tf.constant([[1.,2.], [3.,4.]])
matrix2 = tf.constant([[1.],[2.]])
print("Metrix 1 shape", matrix1.shape)
print("Metrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

Metrix 1 shape (2, 2)
Metrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [26]:
(matrix1 * matrix2).eval() # vs matmul(matrix1, matrix2)

array([[1., 2.],
       [6., 8.]], dtype=float32)

## watch out broadcasting

In [30]:
# Watch out broadcasting - shape이 달라도 연산이 가능해짐(조심해야 함)
matrix1 = tf.constant([[1.,2.]])
matrix2 = tf.constant(3.)
(matrix1+matrix2).eval()

array([[4., 5.]], dtype=float32)

In [31]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [28]:
# Operations between the same shapes
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[5., 5.]], dtype=float32)

## Random values for variable initialization

In [44]:
tf.random_normal([3]).eval()

array([0.54099745, 2.3505936 , 0.15369989], dtype=float32)

In [45]:
tf.random_uniform([2]).eval()

array([0.38906145, 0.16327298], dtype=float32)

In [46]:
tf.random_uniform([2,3]).eval()

array([[0.3442428 , 0.13327575, 0.17877185],
       [0.9063479 , 0.7143601 , 0.9738295 ]], dtype=float32)

## Rduce Mean/Sum

In [34]:
# Rdeuce Mean/Sum
tf.reduce_mean([1,2,], axis=0).eval() # 평균을 구하는데 줄여서 구한다.(integer, float인지 여부에 따라 달라짐)

1

In [35]:
x = [[1.,2.],
    [3.,4.]]

tf.reduce_mean(x).eval()

2.5

In [36]:
tf.reduce_mean(x, axis=0).eval() # axis=0 => (1,3),(2,4) // axis=1 => (1,2),(3,4)

array([2., 3.], dtype=float32)

In [37]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [39]:
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

In [40]:
tf.reduce_sum(x).eval()

10.0

In [41]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [42]:
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [43]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

## Argmax with axis

In [47]:
x = [[0,1,2],
    [2,1,0]]
tf.argmax(x, axis=0).eval() # argmax는 가장 큰 값의 위치를 찾음

array([1, 0, 0], dtype=int64)

In [48]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [49]:
tf.argmax(x,axis=-1).eval()

array([2, 0], dtype=int64)

## Reshape, squeeze, expand_dims

In [50]:
t = np.array([[[0,1,2], # Rank = 3, Shape = (2,2,3)
              [3,4,5]],
             
             [[6,7,8],
             [9,10,11]]])
t.shape

(2, 2, 3)

In [51]:
tf.reshape(t, shape=[-1,3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
tf.reshape(t, shape=[-1,1,3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [53]:
tf.squeeze([[0], [1], [2]]).eval() # 값들을 펴주는거

array([0, 1, 2])

In [54]:
tf.expand_dims([0,1,2], 1).eval() # 차원을 추가해주는거

array([[0],
       [1],
       [2]])

## One hot

In [55]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval(0) # depth는 한 vector의 길이를 정해줌

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [56]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1,3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

## casting

In [57]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval() # integer 값을 바꾸면서 나머지 수를 다 버림

array([1, 2, 3, 4])

In [58]:
tf.cast([True,False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

## Stack

In [59]:
x = [1,4]
y = [2,5]
z = [3,6]

# Pack along first dim
tf.stack([x,y,z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [60]:
tf.stack([x,y,z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

## Ones like and Zeros like

In [61]:
# 0 또는 1 값으로 다 치환
x = [[0,1,2],
    [2,1,0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [62]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

## Zip

In [65]:
for x ,y in zip([1,2,3], [4,5,6]):
    print(x,y)

1 4
2 5
3 6


In [66]:
for x,y,z in zip([1,2,3],[4,5,6],[7,8,9]):
    print(x,y,z)

1 4 7
2 5 8
3 6 9


## Transpose

In [67]:
t = np.array([[[0,1,2], [3,4,5]], [[6,7,8], [9,10,11]]]) # Rank = 3, Shape=(2,2,3)
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [68]:
t1 = tf.transpose(t, [1,0,2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [69]:
t = tf.transpose(t1, [1,0,2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [70]:
t2 = tf.transpose(t, [1,2,0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [71]:
t = tf.transpose(t2, [2,0,1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
